language: node_js
node_js:
  - 6.2.2
services:
  - mysql
before_install:
  - mysql -u root -e "create database IF NOT EXISTS gobble_profile;"
script:
  - npm run lint
  - NODE_ENV=test node server/server.js & npm test